### ISSUE TITLE
Building demo fails with undefined symbol

### ISSUE THREAD

**Issue by ghost** [yotamr/traces#1]
Output: error: unable to load plugin '/home/christer/Source/traces/trace_instrum
entor/trace_instrumentor.so': '/home/christer/Source/traces/trace_instrumentor/t
race_instrumentor.so: undefined symbol: _ZTIN5clang11ASTConsumerE'

**Comment by yotamr** [comment]
What version of clang are you using? 
It should looking something like this:

```
yotam@yotam-ThinkPad-W520:~/Code/traces$ clang -v
clang version 3.0 (tags/RELEASE_30/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by ghost** [comment]
clang version 3.0 (trunk 141852)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by yotamr** [comment]
That's probably it. 
You should use the official 3.0 clang release:
http://llvm.org/releases/3.0/

**Comment by ghost** [comment]
It was. Somehow an old build of clang/llvm was lurking in my PATH.

Debian clang version 3.0-6 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
