### ISSUE TITLE
"script_file" not in local scope, ldwrap.py

### ISSUE THREAD

**Issue by ysangkok** [yotamr/traces#11]
I get an error on this line: https://github.com/yotamr/traces/blob/master/ldwrap.py#L146 complaining that script_file is no global. I added global statements to main() and the linked function and it seems to work, but it doesn't seem like the right solution.

**Comment by yotamr** [comment]
Thanks. Will be resolved soon.

**Comment by ysangkok** [comment]
Closing this since the repo seems to have ceased development and I stopped using this.
