### ISSUE TITLE
demo.o.pp.i doesn't seem to be generated

### ISSUE THREAD

**Issue by ghost** [yotamr/traces#2]
/home/christer/Source/traces/ccwrap.py g++ -I..   -c -o demo.o demo.cpp
demo.o.pp.i crap
g++ -I.. -E -o demo.o.pp demo.cpp -D __TRACE_INSTRUMENTATION -include /home/chri
ster/Source/traces/trace_lib.h -include /home/christer/Source/traces/trace_user.
h
/usr/local/bin/clang -cc1 -Wno-attributes -fcolor-diagnostics -fgnu-keywords -st
d=gnu++11 -x c++ -fcxx-exceptions demo.o.pp -o demo.o.pp.i -I.. -load /home/chri
ster/Source/traces/trace_instrumentor/trace_instrumentor.so -plugin trace-instru
ment
Traceback (most recent call last):
  File "/home/christer/Source/traces/ccwrap.py", line 146, in <module>
    sys.exit(main())
  File "/home/christer/Source/traces/ccwrap.py", line 143, in main
    os.unlink(out_pp_file)
OSError: [Errno 2] No such file or directory: 'demo.o.pp.i'
make: **\* [demo.o] Error 1

**Comment by yotamr** [comment]
Can you run

``````
usr/local/bin/clang -cc1 -Wno-attributes -fcolor-diagnostics -fgnu-keywords -std=gnu++11 -x c++ -fcxx-exceptions demo.o.pp -o emo.o.pp.i -I.. -load /home/christer/Source/traces/trace_instrumentor/trace_instrumentor.so -plugin trace-instrument```
 manually and see whether demo.o.pp.i is generated or whether clang returns an error?

``````

**Comment by ghost** [comment]
I notice that ccwrap.py insists on using /usr/local/bin/clang. That is wrong. That executable doesn't exists anymore.

**Comment by yotamr** [comment]
Yeah, that's probably a problem.
clang path should be taken from the environment.

On Thu, Apr 12, 2012 at 12:48 PM, Christer Stenbrenden <
reply@reply.github.com

**Comment by yotamr** [comment]
Fixed in latest commit

**Comment by ghost** [comment]
I fixed the path to clang in ccwrap.py, which was hard coded to /usr/local/bin/clang, but now i'm back to the previous issue when executing the command you gave:

error: unable to load plugin '/home/christer/Source/traces/trace_instrumentor/tr
ace_instrumentor.so': '/home/christer/Source/traces/trace_instrumentor/trace_ins
trumentor.so: undefined symbol: _ZTIN5clang11ASTConsumerE'

**Comment by yotamr** [comment]
The plugin is probably against the old clang libs. Do a make clean and
compile the plugin again.

Sent from my mobile
On Apr 12, 2012 12:59 PM, "Christer Stenbrenden" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
It was built against debian's clang/llvm packages, which claims to be "clang version 3.0 (tags/RELEASE_30/final)". I uninstalled it and downloaded the official debian build from llvm and now everything works. Seems to be a bug in the debian packages.
