### ISSUE TITLE
How to enable func enter/leave printing?

### ISSUE THREAD

**Issue by mo** [yotamr/traces#4]
The README file says "to produce verbose output showing function entry/leave, use the '-f' parameter".
But what filter should be passed to -f in this case? Or did you mean to write "-d" instead of "-f" because if I pass "-d" to trace_dumper I do get func enter/leave reported.

**Comment by yotamr** [comment]
You're right, the README is incorrect, '-d' does the trick.

**Comment by yotamr** [comment]
Fixed in d6e14f8c736d4660cf71a12c7cbb76d481c4a04d
