### ISSUE TITLE
Clang version requirements

### ISSUE THREAD

**Issue by akariv** [yotamr/traces#7]
It seems that it really has to be exactly 3.0 -

It won't compile with clang 2.7
It won't compile with clang 3.2

I think it's a little restrictive. Either way I'd add a note about it.

**Comment by yotamr** [comment]
Yeah, you're probably right.
You should use the clang 3.0 binaries:
http://llvm.org/releases/download.html

I'll update the wiki, thanks

On Sat, Apr 21, 2012 at 6:38 PM, akariv <
reply@reply.github.com
